services:
  # ASP.NET Core API
  - type: web
    name: appointment-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Web-Api/AppointmentApp/Dockerfile
    dockerContext: ./Web-Api
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_HTTP_PORTS
        value: "8080"
      - key: ConnectionStrings__DefaultConnection
        sync: false

  # ASP.NET Core Web App
  - type: web
    name: appointment-web
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Web-App/AppointmentApp/Dockerfile
    dockerContext: ./Web-App
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_HTTP_PORTS
        value: "8080"
      - key: ApiSettings__BaseUrl
        fromService:
          type: web
          name: appointment-api
          envVarKey: RENDER_EXTERNAL_URL
